version: '2'
services:
  db:
    build: ../dockerfiles/db
    image: docker-ror_db_dev
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - rails_db:/var/lib/mysql


  web:
    build: 
      context: ../dockerfiles/web
      dockerfile: "Dockerfile_centos7"
      args:
        - RAILS_ENV=development
    image: docker-ror_web_dev
    ports:
      - "8888:80"
    volumes:
      - ../../source:/var/rails_app
    privileged: true


volumes:
  rails_db:
    driver: 'local'
