version: '2'
services:
  db:
    build:
      context: ../dockerfiles/db
      dockerfile: "Dockerfile"
    environment: 
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - rails_db:/var/lib/mysql
    restart: always

  web:
    build: 
      context: ../dockerfiles/web
      dockerfile: "Dockerfile_centos7"
      args:
        - RAILS_ENV=production
        - SECRET_KEY_BASE=xxxyyyzzz
        - DB_HOST=db
        - DB_USERNAME=root
        - DB_PASSWORD=root
    ports:
      - "80:80"
    volumes:
      - ../../source:/var/rails_app
      - applog:/var/rails_app/log
      - rubygems:/var/rails_app/vendor
      - node_modules:/var/rails_app/public/node_modules
    privileged: true
    restart: always

volumes:
  rails_db:
    driver: 'local'
  applog:
    driver: 'local'
  rubygems:
    driver: 'local'
  node_modules:
    driver: 'local'
