version: '3'
services:
  db:
    build:
      context: ../dockerfiles/db
      dockerfile: "Dockerfile"
    environment: 
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - rails_db:/var/lib/mysql
    restart: always

  web:
    build: 
      context: ../dockerfiles/web
      dockerfile: "Dockerfile_centos7"
      args:
        - RAILS_ENV=production
    volumes:
      - ../../../:/var/www/app
      - os_log:/var/log
    privileged: true
    restart: always

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: "${MY_DOMAIN} -> http://web"
      STAGE: 'production'
    restart: always

volumes:
  rails_db:
    driver: 'local'
  os_log:
    driver: 'local'

