version: '2'
services:
  db:
    build:
      context: ../dockerfiles/db
      dockerfile: "Dockerfile"
    container_name: "rails_prd_db_1"
    environment: 
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - rails_db:/var/lib/mysql
    restart: always

  web:
    build: 
      context: ../dockerfiles/web
      dockerfile: "Dockerfile_centos7"
      args:
        - RAILS_ENV=production
    container_name: "rails_prd_web_1"
    ports:
      - "80:80"
    volumes:
      - ../../../:/var/my_dir
      - os_log:/var/log
    privileged: true
    restart: always

volumes:
  rails_db:
    driver: 'local'
  os_log:
    driver: 'local'

