version: '2'
services:
  db:
    build:
      context: ../dockerfiles/db
      dockerfile: "Dockerfile"
    environment: 
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - rails_db:/var/lib/mysql


  web:
    build: 
      context: ../dockerfiles/web
      dockerfile: "Dockerfile_centos7"
      args:
        - RAILS_ENV=development
    ports:
      - "8888:80"
      - "1233:1233"
      - "3003:3003"
    volumes:
      - ../../source:/var/rails_app
      - os_log:/var/log
    privileged: true


  mail: # 開発環境用のメールサーバ
    image: sj26/mailcatcher
    ports:
      - "1080:1080"

volumes:
  rails_db:
    driver: 'local'
  os_log:
    driver: 'local'