version: '2'
services:
  db:
    build:
      context: ../dockerfiles
      dockerfile: "db_Dockerfile"
    env_file: ../dockerfiles/.env
    volumes:
      - rails_db:/var/lib/mysql


  web:
    build: 
      context: ../dockerfiles
      dockerfile: "web_Dockerfile_centos7"
      args:
        - RAILS_ENV=development
    ports:
      - "8888:80"
    volumes:
      - ../../source:/var/rails_app
    privileged: true


volumes:
  rails_db:
    driver: 'local'
